[package]
name = "quicfs-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = { version = "0.4", features = ["std"]}
env_logger = "0.9.0"
url = "2.2"
tokio = { version = "1.21.0", features = ["macros", "rt-multi-thread"] }
clap = { version = "3.2.20", features = ["derive"] }
