[package]
name = "quicfs-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "~2.34"
log = { version = "0.4", features = ["std"]}
env_logger = "0.9.0"
qp2p = "0.30.0"
url = "2.2"
